version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always  
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}
    volumes:
      - .:/app  
      - /app/node_modules
    command: npm run start:dev  
    networks:
      - app-network  
         
  postgres:
    image: postgres:latest
    container_name: postgresSQL
    ports:
      - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network  
  
networks:
  app-network:
    driver: bridge  